language: python
python:
  - "2.7"
  - "3.4"
notifications:
  email: false

# Setup anaconda
before_install:
  # Install conda
  - pip install conda
  # install deps
  - conda init
  - conda update conda --yes
  - deps='pip scipy numpy pandas'
  - conda create -p $HOME/conda --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/conda/bin:$PATH

# Install dependencies
install: "pip install -r requirements.txt"

# Run tests
script: "python -m unittest discover"
