language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# For numpy and scipy support
virtualenv:
      system_site_packages: true
# Install numpy and scipy
before_install:
  - sudo apt-get install -qq python-numpy python-scipy python-pandas
# command to run tests
script: "python -m unittest discover"
