language: python
python:
  - "2.7"
  - "3.4"
notifications:
  email: false

# Setup anaconda
# Based on http://dan-blanchard.roughdraft.io/7045057-quicker-travis-builds-that-rely-on-numpy-and-scipy-using-miniconda
before_install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy pandas

# Install dependencies
install: 
  - pip install -r requirements.txt
  - python -V

# Run tests
script: "python -m unittest discover"

# Only build master branch
branches:
  only:
    - master
